# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Imod
                                 A QGIS plugin
 A plugin to visualize 4D geospatial data, catered to groundwater modellers 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-03
        copyright            : (C) 2021 by Deltares
        email                : joeri.vanengelen@deltares.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Imod class from file Imod.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .imod_plugin import Imod
    return Imod(iface)
