# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImodDockWidget
                                 A QGIS plugin
 A plugin to visualize 4D geospatial data, catered to groundwater modellers 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-03
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Deltares
        email                : joeri.vanengelen@deltares.nl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

from .maptools import RectangleMapTool

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'qt', 'imod_plugin_dockwidget_base.ui'))


class ImodDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, canvas, parent=None):
        """Constructor."""
        super(ImodDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        #Viewer
        #self.LayerSelect.clicked.connect(self.layer_select)
        self.DrawExtent.clicked.connect(self.draw_extent)
        #self.ExtentBox <- What to do with this?
        self.StartViewer.clicked.connect(self.start_viewer)
        self.canvas = canvas

        self.bbox = None #TODO: Get viewextent, use qgis-tim as example
        self.rectangleTool = RectangleMapTool(self.canvas)
        self.rectangleTool.rectangleCreated.connect(self.get_bbox)

    def layer_select(self):
        pass

    def get_bbox(self):
        self.bbox = self.rectangleTool.bbox
        print(self.bbox)

    def draw_extent(self):
        print("Please draw extent")
        self.canvas.setMapTool(self.rectangleTool)

    def start_viewer(self):
        pass

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()